version: "3.8"
services:
  conduit-web-angular:
    image: gachlab/conduit-web-angular:latest
    build:
      context: .
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 4200    
    labels:
      traefik.http.routers.conduit-web-angular.rule: Host(`angular-conduit.${GACHLAB_DOMAIN}`)
      traefik.http.routers.conduit-web-angular.tls.certresolver: "le"
      traefik.http.routers.conduit-web-angular.entrypoints: "websecure"
networks: 
  default:
    external: 
      name: gcarrillo_default