import { Injectable } from '@angular/core';

@Injectable()
export class ConduitPagesHomeService {

  articles = {
    articles: [
      {
        title: 'Article one',
        slug: 'article-one-6hwnpe',
        body: 'Article one',
        createdAt: '2020-07-01T04:41:43.134Z',
        updatedAt: '2020-07-01T04:41:43.134Z',
        tagList: [],
        description: 'Nothing',
        author: {
          username: 'bima',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 1,
      },
      {
        title: 'title1',
        slug: 'title-5g7c8r',
        body: 'body',
        createdAt: '2020-07-01T04:32:04.160Z',
        updatedAt: '2020-07-01T05:15:44.183Z',
        tagList: [],
        description: 'descr',
        author: {
          username: 'AnnaUmi',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
      {
        title: 'My article about react',
        slug: 'my-article-about-react-5lcz5i',
        body: ':))',
        createdAt: '2020-07-01T04:06:40.120Z',
        updatedAt: '2020-07-01T04:06:40.120Z',
        tagList: [],
        description: 'How much I hate Vue :p ',
        author: {
          username: 'dieguer',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
      {
        title: 'Title',
        slug: 'title-m1ow39',
        body: 'This is title.',
        createdAt: '2020-07-01T04:02:43.483Z',
        updatedAt: '2020-07-01T04:02:43.483Z',
        tagList: [],
        description: 'About title',
        author: {
          username: 'Meigo Kukk',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
      {
        title: 'Test',
        slug: 'test-g3lc10',
        body: 'Test 2',
        createdAt: '2020-07-01T03:29:37.236Z',
        updatedAt: '2020-07-01T03:29:37.236Z',
        tagList: [],
        description: 'Test 1',
        author: {
          username: 'maxiCoronel',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
      {
        title: 'First Article',
        slug: 'first-article-zwf3cb',
        body: 'This my 1st Article.',
        createdAt: '2020-07-01T03:18:19.672Z',
        updatedAt: '2020-07-01T03:18:19.672Z',
        tagList: [],
        description: 'About 1st Article',
        author: {
          username: 'Srijana Shrestha',
          bio: null,
          image: '',
          following: false,
        },
        favorited: false,
        favoritesCount: 1,
      },
      {
        title: 'First Article',
        slug: 'first-article-61tyfd',
        body: 'This my 1st Article.',
        createdAt: '2020-07-01T03:17:43.652Z',
        updatedAt: '2020-07-01T03:17:43.652Z',
        tagList: [],
        description: 'About 1st Article',
        author: {
          username: 'Srijana Shrestha',
          bio: null,
          image: '',
          following: false,
        },
        favorited: false,
        favoritesCount: 1,
      },
      {
        title: 'First Article',
        slug: 'first-article-ontex6',
        body: 'This my 1st Article.',
        createdAt: '2020-07-01T03:16:37.900Z',
        updatedAt: '2020-07-01T03:16:37.900Z',
        tagList: [],
        description: 'About 1st Article',
        author: {
          username: 'Srijana Shrestha',
          bio: null,
          image: '',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
      {
        title: 'New Article blah blahblah blahblah blah!!!',
        slug: 'new-article-blah-blahblah-blahblah-blah-xz6fh4',
        body:
          'blah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blahblah blah\n\nHello world!!!!! :)',
        createdAt: '2020-07-01T02:45:59.469Z',
        updatedAt: '2020-07-01T02:45:59.469Z',
        tagList: ['hello world', 'blah blah blah blah', 'blah blah', 'blah'],
        description: 'blah blahblah blah!!',
        author: {
          username: 'HanJM',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 1,
      },
      {
        title: 'Test Article',
        slug: 'test-article-59o7jn',
        body: 'This is a test article',
        createdAt: '2020-07-01T01:34:11.609Z',
        updatedAt: '2020-07-01T01:34:11.609Z',
        tagList: [],
        description: 'Test Creation',
        author: {
          username: 'Alex41790',
          bio: null,
          image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
          following: false,
        },
        favorited: false,
        favoritesCount: 0,
      },
    ],
    articlesCount: 500,
  };
  tags = {
    tags: [
      'SIDA',
      'HITLER',
      'test',
      'butt',
      'dragons',
      'training',
      'tag1',
      'tag2',
      'tags',
      'as',
      'coffee',
      'animation',
      'baby',
      'money',
      'cars',
      'flowers',
      'japan',
      'caramel',
      'happiness',
      'sushi',
    ],
  };

  init() {
    return Promise.resolve(Object.assign({}, this.tags, this.articles));
  }
}
